### ISSUE TITLE
Regex issue with current search filter

### ISSUE THREAD

**Issue by MartinFestingerVault** [FestingerVault/festingervault#37]
I believe there is a regex coded way too hard to find the exact word/character

For Example, to find Essential Addons for Elementor, I had to delete the word “Elementor” in the search bar because I had it was typed as “Elementor Essent-”, this is a typical regex coding and quite a difficult thing to get right, mostly because it is trying to match the characters in the exact order to avoid non sense results.

My logic which worked for my AI Logo site, which I used for word filtering to avoid any NSFW or misuse, was to let full or mid “words” be in any place as long as it is preceeded or after a “space”. Worked wonders for me, if you guys need, I could share the coding I did for it.

https://meta.festingervault.com/t/its-here-the-all-new-festinger-vault-plugin-is-ready-for-download/99904/136?u=martin

**Comment by RevvyBeats** [comment]
Greetings, I was the one to point it out, I sent out an email, I will also include the important stuff here just in case it could solve other problems I have read through! Reach for me any time you need me, will happily help!

I would like to share if it is any help, my logic and the files for the React Project I made, I will attach a few screenshots to make it easier to understand, and also if you guys have any questions, please, don't hesitate to ask, I love your work guys and would be an honor to even just help. This email may be kind of lengthy due to how this logic worked, I have to start from the bottom.

1. Our Site Needed a Word Filter so there were no NSFW/Weird Generations going on. One of the developers made a simple banned word list inside our react js project folder exactly in:
**.\apps\web\server\routers** named **router.constants.ts**

router.constants.ts is fairly straight forward, I won't post the full word list, only the logic it used:
```typescript
export const bannedWords: string[] = [
// Banned Words List
];
``` 

2. The main generation router in the same folder named generations.router.ts where it would check for any inconsistency (Credits Left, Subscription, WORD FILTER) and return the generated image in Hartsy's case. Make the app recognize these words, case insensitive and NOW the main problem I noticed here, he coded a regex that for example, a word I wanted to generate was "BRAND" it threw an error due to the word CONTAINING the banned word "BRA", so I made this logic after the banned words list.

```typescript
// We import ./router.constants bannedWords

import { bannedWords } from "./router.constants";

// MAIN REGEX LOGIC
// Searches through ./router.constants, puts every word into lower case, replaces spaces (here is where this might be useful) 
// in phrases, and makes spaces don't matter if they are before, in between another phrase or word, etc.
// this I believe is a key point if the search is using regex mostly, below, I will leave the code I used to fix what the other developer couldn't.

// Adjusted function using regex for accurate word boundary checks
const containsBannedContent = (inputText: string, bannedList: string[]): boolean => {
  return bannedList.some(banned => {
    // eslint-disable-next-line unicorn/prefer-string-replace-all
    const regex = new RegExp(`\\b${banned.replace(/ /g, "\\s")}\\b`, "i"); // Replace spaces in phrases with \s to match any whitespace, and 'i' for case insensitive
    return regex.test(inputText);
  });
};

// In here, it will check if it contains any banned words and if was written in the text field, the result is a boolean. 
// If the result is positive, an error will display, if the result if false, it will continue to the generation of the image process

      if(!isTemplate && containsBannedContent(positive, bannedWords)) {
        throw new TRPCError({ code: "UNPROCESSABLE_CONTENT", message: "Input contains a banned word or phrase." });
      }

// The code is extremely extensive, I tried to only put the regex fix logic that I believe is the best way to fix the problem, regex is quite good, but resource consuming.
``` 

I really hope for you guys to hit me back if I was able to help, I will look through the code in festinger vault github project and see if I can fix it myself but first I will try to wait for you before a pull request or anything.

I am open on sharing the code, helping with issues, etc.
-Revvy

**Comment by MartinFestingerVault** [comment]
Hi @RevvyBeats,

The current 'search' is actually a filter - and it will be replaced with the TypeSense one. 

https://github.com/FestingerVault/festingervault/issues/4
