### ISSUE TITLE
Search improvement + issue

### ISSUE THREAD

**Issue by MartinFestingerVault** [FestingerVault/festingervault#61]
When you finish typing “Elementor”, the search is triggered and the cursor returns to outside the search field. The ideal would be to return to the end of the word that was being searched. It would make it easier to continue the search. I think I saw a similar suggestion from another member, right?

![Image](https://github.com/user-attachments/assets/5121b777-23b7-4253-bbe3-dde771c8c21a)

https://meta.festingervault.com/t/its-here-the-all-new-festinger-vault-plugin-is-ready-for-download/99904/150?u=martin

**Comment by Risengan** [comment]
### Another suggestion for improving search

Can you improve the regex so that the search takes spaces and some typos into account?
Here's an example that happened to me:

I searched for the **JetSmartFilters** plugin from Crocoblock (there's no space) and the first time I couldn't find it because it was named **Jet Smart Filters** on Festinger Vault.

https://github.com/user-attachments/assets/2c2a71e0-eca0-46c3-b227-eeeaecb53937

Another possible improvement would be to accept one or two typos to find the result:

https://github.com/user-attachments/assets/a68549f1-f3c5-4371-9f47-51ea3209500f

Hope this helps :)

**Comment by ssovit** [comment]
Items search would be replaced with typesense.

**Comment by hansschuijff** [comment]
I find the most irritating problem that I can't just copy and paste the original plugins/theme name as installed in WordPress and trust that search will find it.  Often I need to edit the pasted name to make FV find it.

Why doesn't FV just use the literal plugin/theme names and sometimes changes word order of inserts something so the original plugin name is not found? It could prepend of append the developer when needed, but why change a name so it won't be found by its literal name?

Example: Advanced Custom Fields Pro is not found, since in FV it is called Advanced Custom Fields (ACF) Pro. It finds two other plugins that are not called Advanced Custom Fields Pro instead. I need either delete the pro part or add the (ACF) part to find the plugin.

And some plugins have changed the word WooCommerce in simply Woo in their names, since WooCommerce self was converting to that (and by now seems to revert that since woo.com didn't get the same trafic), but they are not found by their actual plugin name too.

IMO FV should always be able to find a plugin or theme by the name they actually call themselves.

**Comment by MartinFestingerVault** [comment]
We started developing the universal search using TypeSense. 

https://github.com/FestingerVault/festingervault/issues/4

As it will work with Regex - all feedback by @hansschuijff and @Risengan will be included.
