### ISSUE TITLE
Option to remove enable automatic updates

### ISSUE THREAD

**Issue by MartinFestingerVault** [FestingerVault/festingervault#62]
Regarding automatic updates in the WP Plugins menu, the ideal would be to remove the “Enable Automatic Update” option. This way, neither the user (our client) nor WP itself could activate updates in this menu - ONLY FOR PLUGINS INSTALLED FROM THE FESTINGER VAULT PLUGIN.
This option would also prevent the update of free plugins such as Elementor Free, which we use together with Elementor Pro, from Festinger.

![Image](https://github.com/user-attachments/assets/406623b3-39ea-4776-97e2-8d7560ddde4e)

https://meta.festingervault.com/t/its-here-the-all-new-festinger-vault-plugin-is-ready-for-download/99904/150?u=martin

**Comment by hansschuijff** [comment]
Involving free versions that are coupled to the premium products in FV would add a level of complication, and there are more plugins that have such relationships except Elementor Pro. 

I mentioned earlier that Tribe's Event Tickets is coupled to Events Tickets Plus and often needs to be updated at the same time (probably when the included common code that's included in both has incompatible changes) and the same is true for The Events Calendar and The Events Calender Pro. Probably there are many more and if you enter the path of having knowledge of such relations it may lead to having to make the next steps too, what you may or may not want to add to the workload.

Thinking about this issue, one could go more radical and just replace the entire plugins menu-items of WordPress by a FestingerVault installe/update page that shows and handles both. Perhaps that would not be as big a change as one might think and may just mean each product is pointed to actions by either WP of FV.

Right now the management of plugins is split depending on the source what is always a lesser solution for people that need to manage updates and installs. Making some integrated version that can handle both and uses WordPress core or custom code depending on the plugin may be an elegant solution. Site managers would perhaps be createfull if they only need to visit one list instead of having to split their attention.

Probably it would mean a separation between plugins and themes again, but that would not be too unsolvable. It might even be an improvement over the normal wordpress plugins functionality.

Would be something too think about.

**Comment by ssovit** [comment]
@hansschuijff thank you for your feedback.

Yes, having auto update to a pro version and their free counterpart lagging behind, shouldn't be an issue since almost all premium plugins that extend their free versions doesn't make breaking changes and supports older versions of free version they host in wp.org, or prompt to do update if required and important.

FV plugin doesn't provide auto update for plugins hosted on wp.org unless the free version requires some changes made to make premium version work (like with Elementor free that required some changes made on free version for pr version work at some point of time and sometimes the activator plugin is provided as demo/additional content for the plugin/theme).

Auto-updates enabled on FV plugin's updates table would use FestingerVault update channel to perform updates, and it cannot be mixed up with WP's Core plugins' automatic updates process.

**Comment by hansschuijff** [comment]
Helas, the plugins I mentioned often don't load based on versions, so that's why I can't use auto-update for those. Most of the time they need to be updated together. Sensei Pro solves that by including the free (base) version in the pro version, what is a lot nicer.

Apart from that, it seems we are not connecting, but that is okay. I was just fantasising about something new, that would combine the windows plugins page with festinger vault so all plugins could be mananaged in a single integrated page. But that is somewhat an aside for this issue.

**Comment by ssovit** [comment]
I do connect with you. 

But FV plugin shall not be alternative to WP's core auto-update pipeline. Instead it would have it's own channel and update the items you select to be updated when new version is available after being verified working via FV engine. If you would like any of the plugin's counterpart that needs to be available for auto-update when a plugin's update is available, please let us know, so we can make sure both updates are posted simultaneously.

**Comment by hansschuijff** [comment]
Only the two I mentioned. When updating to the latest version of The Events Calendar Pro also the latest version of The Events Calendar is needed (if not already active) and when updating to the latest version of Events Calendar plus, the latest version of Event Tickets is needed. 

Sometimes the base plugins can be updated separately, but all to often the are coupled too tight to do so and need to be updated as a couple. It means that when one is updated without the other, the plugins stop functioning and wait for the other to update.

Personally I don't like that kind of tight coupling between plugin versions, but that is how tribe does it. Having FV auto-update both plugins in combination will be helpfull.

N.b. when you would automate to update the combo, perhaps it also should be visible in the updates page that you will do so.

**Comment by hansschuijff** [comment]
I was thinking about removing the default WordPress autoupdate link, and that is probably a good idea, but there is a border case.

I have plugins and themes that are available in the vault, for which I have a payed (lifetime) license. Updating such plugins should be performed through the original source, not FV, or at least that option should be available. When plugins should never update by FV the autoupdate in windows should not be removed.

There should be some mechanism to mark those products in the updates page, so FV can hide them and leave them be in WordPress.

**Comment by ssovit** [comment]
Hi,

Yes, I do agree with you, if you have a permanent license for some plugins and they shouldn't be updated by FV plugin if you don't choose to. The auto-update switcher is added for the reason so you can personally choose which plugin/theme you want to be updated using FV plugin and others would be ignored during the auto-update cycle.

But, in future, there would sure be option in settings page of the plugin UI where you can choose which plugin/themes you want the FV plugin to watch and whom to ignore. This way, the plugin updates page UI of FV plugin would only contain the update information on your watchlist.

About WP's core auto-update feature, we may consider it but not at the moment.

**Comment by MartinFestingerVault** [comment]
We have added the feature request to ignore a plugin/theme for auto-update here: 
https://github.com/FestingerVault/festingervault/issues/32
